### Question All List ###
GET localhost:5000/question
Authorization: capybara
### Question Content List ###
GET localhost:5000/question/60e5f9118f43e81c2cafe142
Authorization: capybara
### Question Creation ###
POST localhost:5000/question/
Authorization: capybara
Content-Type: application/json

{
  "category": "Animals",
  "title": "Is Capybara beautiful?",
  "optionalSubContent": "",
  "answerTypology": "text"
}
### Question Edit ###
PUT localhost:5000/question/60e5f9118f43e81c2cafe142
Authorization: capybara
Content-Type: application/json

{
  "category": "Animals",
  "title": "Is Capybara beautiful?",
  "optionalSubContent": "Be careful, there are more correct choices!",
  "answerTypology": "multi",
  "answers": [
    {
      "text": "Yes",
      "isCorrect": true
    },
    {
      "text": "Yes, of course",
      "isCorrect": true
    },
    {
      "text": "Yes, it's a divine animal",
      "isCorrect": true
    },
    {
      "text": "Yes, yes my owner~",
      "isCorrect": true
    }
  ]
}
### Category Delete ###
DELETE localhost:5000/question/60e5f7c76cab53085003e898
Authorization: capybara
###
