### Category All List ###
GET localhost:5000/category
Authorization: capybara
### Category Content List ###
GET localhost:5000/category/:catName
Authorization: capybara
### Category Update Name ###
PUT localhost:5000/category/:catName
Authorization: capybara
Content-Type: application/json

{
  "name": "BestAnimals"
}
### Category Delete ###
DELETE localhost:5000/category/:catName
Authorization: capybara
###
